#  web设置
server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
spring:
#  数据库
  datasource:
    url: jdbc:mysql://localhost:3306/fams?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
    cache: false
  main:
    allow-bean-definition-overriding: true
mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
#   日志
logging:
  level:
    xyz:
      kakusei:
        fams:
          service: info
          mapper: debug
#   分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql