server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fams?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
    cache: false
mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml

logging:
  level:
    xyz:
      kakusei:
        fams:
          mapper: debug
          service: debug
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql


